// default package
// Generated Oct 18, 2024, 8:39:26 PM by Hibernate Tools 4.3.6.Final

package com.demo.entities;

import java.util.List;

import jakarta.persistence.*;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "shoes")
public class Product implements java.io.Serializable {

	private Integer id;
	private String sku;
	private String description;
	private float price;
	private float listPrice;
	private float originalPrice;
	private String sizes;
	private String colors;
	private float discount;
	private double discountRate;
	private int reviewCount;
	private String inventoryStatus;
	private int stockItemMaxSaleQty;
	private String productName;
	private int branchId;
	private String branchName;
	private String thumbnailUrl;
	private String urlKey;
	private String urlPath;
	private double ratingAverage;
	private String images;


	public Product() {
	}

	public Product(String sku, String description, float price, float listPrice, float originalPrice, String sizes,
			String colors, float discount, double discountRate, int reviewCount, String inventoryStatus,
			int stockItemMaxSaleQty, String productName, int branchId, String branchName, String thumbnailUrl,
			String urlKey, String urlPath, double ratingAverage, String images) {
		this.sku = sku;
		this.description = description;
		this.price = price;
		this.listPrice = listPrice;
		this.originalPrice = originalPrice;
		this.sizes = sizes;
		this.colors = colors;
		this.discount = discount;
		this.discountRate = discountRate;
		this.reviewCount = reviewCount;
		this.inventoryStatus = inventoryStatus;
		this.stockItemMaxSaleQty = stockItemMaxSaleQty;
		this.productName = productName;
		this.branchId = branchId;
		this.branchName = branchName;
		this.thumbnailUrl = thumbnailUrl;
		this.urlKey = urlKey;
		this.urlPath = urlPath;
		this.ratingAverage = ratingAverage;
		this.images = images;

	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sku", nullable = false, length = 250)
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "list_price", nullable = false, length = 65535)
	public float getListPrice() {
		return this.listPrice;
	}

	public void setListPrice(float listPrice) {
		this.listPrice = listPrice;
	}

	@Column(name = "original_price", nullable = false, precision = 12, scale = 0)
	public float getOriginalPrice() {
		return this.originalPrice;
	}

	public void setOriginalPrice(float originalPrice) {
		this.originalPrice = originalPrice;
	}

	@Column(name = "sizes", nullable = false, length = 65535)
	public String getSizes() {
		return this.sizes;
	}

	public void setSizes(String sizes) {
		this.sizes = sizes;
	}

	@Column(name = "colors", nullable = false, length = 65535)
	public String getColors() {
		return this.colors;
	}

	public void setColors(String colors) {
		this.colors = colors;
	}

	@Column(name = "discount", nullable = false, precision = 12, scale = 0)
	public float getDiscount() {
		return this.discount;
	}

	public void setDiscount(float discount) {
		this.discount = discount;
	}

	@Column(name = "discount_rate", nullable = false, precision = 22, scale = 0)
	public double getDiscountRate() {
		return this.discountRate;
	}

	public void setDiscountRate(double discountRate) {
		this.discountRate = discountRate;
	}

	@Column(name = "review_count", nullable = false)
	public int getReviewCount() {
		return this.reviewCount;
	}

	public void setReviewCount(int reviewCount) {
		this.reviewCount = reviewCount;
	}

	@Column(name = "inventory_status", nullable = false, length = 250)
	public String getInventoryStatus() {
		return this.inventoryStatus;
	}

	public void setInventoryStatus(String inventoryStatus) {
		this.inventoryStatus = inventoryStatus;
	}

	@Column(name = "stock_item_max_sale_qty", nullable = false)
	public int getStockItemMaxSaleQty() {
		return this.stockItemMaxSaleQty;
	}

	public void setStockItemMaxSaleQty(int stockItemMaxSaleQty) {
		this.stockItemMaxSaleQty = stockItemMaxSaleQty;
	}

	@Column(name = "product_name", nullable = false, length = 250)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "branch_id", nullable = false)
	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	@Column(name = "branch_name", nullable = false, length = 250)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "thumbnail_url", nullable = false, length = 65535)
	public String getThumbnailUrl() {
		return this.thumbnailUrl;
	}

	public void setThumbnailUrl(String thumbnailUrl) {
		this.thumbnailUrl = thumbnailUrl;
	}

	@Column(name = "url_key", nullable = false, length = 65535)
	public String getUrlKey() {
		return this.urlKey;
	}

	public void setUrlKey(String urlKey) {
		this.urlKey = urlKey;
	}

	@Column(name = "url_path", nullable = false, length = 65535)
	public String getUrlPath() {
		return this.urlPath;
	}

	public void setUrlPath(String urlPath) {
		this.urlPath = urlPath;
	}

	@Column(name = "rating_average", nullable = false, precision = 22, scale = 0)
	public double getRatingAverage() {
		return this.ratingAverage;
	}

	public void setRatingAverage(double ratingAverage) {
		this.ratingAverage = ratingAverage;
	}

	@Column(name = "images", nullable = false, length = 65535)
	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	

}
